import { ExperimentalUIWrapper,
         StyleBneonCard,
         StyleProfileWrapper,
         CardWrapper,
         StyledWrapper,
         ProfileCardCenterButton,
         ProfileCardContainer,
         ProfileCardInner,
         ProfileItemInnerSpan,
         ProfileItemReact,
         ProfileItemBase,
         ProfileItemAws,
         ProfileItemPython,
         ProfileItemJs,
         IconJsCustom,
         IconTwentyEight,
         ProfileItemWordpress,
         ProfileItemAngular,
         ProfileItemGitAlt,
         IconWordpressCustom,
         IconAngularCustom,
         IconReactCustom,
         IconGitAltCustom,
         StyleSocialWrapper,
         StyledSci,
         SocialTitle,
         SocialContent,
         CollaborationsWrapper,
         AnimationWrapper,
         CollabWrapper,
         FooterWrapper,
         TopSection,
         BrandInfo,
         Logo,
         LogoIcon,
         Tagline,
         NavColumns,
         NavColumn,
         BottomSection,
         Copyright,
         PolicyLinks,
         MainChart,
         loading90,
         CommitCard,
         GitChartWrapper,
         CardContainer,
         SpeenKeyFrames,
         Spin,
         ProfilePictureImg } from "./styled.components";

/**Portfolio-erick - version 35.18 - styled.components - Features:
 * 
 *      --> Importing and exporting 'Spin'
 * 
 * Notes: This components is adapted to the new layout
 * and is functional working, pending for layout the 
 * component itself
 */

export { ExperimentalUIWrapper,
         Spin,
         CardContainer,
         SpeenKeyFrames,
         GitChartWrapper,
         loading90,
         CommitCard,   
         MainChart,
         PolicyLinks,
         Copyright,
         BottomSection,
         Tagline,
         NavColumn,
         NavColumns,
         TopSection,
         LogoIcon,
         Logo,
         BrandInfo,
         CollabWrapper,
         FooterWrapper,
         StyleProfileWrapper,
         StyleBneonCard,
         CardWrapper,
         StyledWrapper,
         ProfilePictureImg,
         ProfileCardCenterButton,
         ProfileCardContainer,
         ProfileCardInner,
         ProfileItemInnerSpan,
         ProfileItemReact,
         ProfileItemBase,
         ProfileItemAws,
         ProfileItemPython,
         ProfileItemJs,
         IconJsCustom,
         IconTwentyEight,
         ProfileItemWordpress,
         ProfileItemAngular,
         ProfileItemGitAlt,
         IconWordpressCustom,
         IconAngularCustom,
         IconReactCustom,
         IconGitAltCustom,
         StyleSocialWrapper,
         StyledSci,
         SocialTitle,
         CollaborationsWrapper,
         SocialContent,
         AnimationWrapper
         }

