import { ExperimentalUIWrapper,
         StyleBneonCard,
         StyleProfileWrapper,
         CardWrapper,
         StyledWrapper,
         ProfileCardCenterButton,
         ProfileCardContainer,
         ProfileCardInner,
         ProfileItemInnerSpan,
         ProfileItemReact,
         ProfileItemBase,
         ProfileItemAws,
         ProfileItemPython,
         ProfileItemJs,
         IconJsCustom,
         IconTwentyEight,
         ProfileItemWordpress,
         ProfileItemAngular,
         ProfileItemGitAlt,
         IconWordpressCustom,
         IconAngularCustom,
         IconReactCustom,
         IconGitAltCustom,
         StyleSocialWrapper,
         StyledSci,
         SocialTitle,
         SocialContent,
         CollaborationsWrapper,
         TypingKeyFrame,
         BlinkCaretKeyframe,
         AnimationWrapper,
         ProfilePictureImg } from "./styled.components";

/**Portfolio-erick - version 32.06 - styled.components - Features:
 * 
 *      --> Importing and exporting 'AnimationWrapper'
 * 
 * Notes: This components is adapted to the new layout
 * and is functional working, pending for layout the 
 * component itself
 */

export { ExperimentalUIWrapper,
         BlinkCaretKeyframe,
         StyleProfileWrapper,
         StyleBneonCard,
         CardWrapper,
         StyledWrapper,
         ProfilePictureImg,
         ProfileCardCenterButton,
         ProfileCardContainer,
         ProfileCardInner,
         ProfileItemInnerSpan,
         ProfileItemReact,
         ProfileItemBase,
         ProfileItemAws,
         ProfileItemPython,
         ProfileItemJs,
         IconJsCustom,
         IconTwentyEight,
         ProfileItemWordpress,
         ProfileItemAngular,
         ProfileItemGitAlt,
         IconWordpressCustom,
         IconAngularCustom,
         IconReactCustom,
         IconGitAltCustom,
         StyleSocialWrapper,
         StyledSci,
         SocialTitle,
         CollaborationsWrapper,
         SocialContent,
         TypingKeyFrame,
         AnimationWrapper
         }

